Add compatibility to CAF benchmark suite
shamsimam/savina pull request #8
Opened 2017-06-21 15:53 UTC by aufgang001

Existing scripts which use savina are not effected by this pull request.
CLI Arguments are now handled by the class CliArgumentParser, which generalises and simplifies parsing of arguments.
And a new CLI arg for the benchmark runner is added (--no_evaluation) which deactivates performance calculations and output.

2017-08-01 03:40 UTC, shamsimam requested changes
In general, I like the `CliArgumentParser` and that it reduces lots of boiler plate elsewhere in the code. However, I requested some changes to be able to reuse code inside the `CliArgumentParser` implementation.

2017-08-01 03:40 UTC, shamsimam commented on src/main/java/edu/rice/habanero/benchmarks/BenchmarkRunner.java
> +        no_evaluation = argParser.getValue(new String[]{"--no_evaluation"}, no_evaluation);
Can we please use `no-evaluation`?

2017-08-01 03:40 UTC, shamsimam commented on src/main/java/edu/rice/habanero/benchmarks/BenchmarkRunner.java
> +    protected static boolean no_evaluation = false;
I would prefer camel case in the naming of variables, e.g. `noEvaluation`

2017-08-01 03:40 UTC, shamsimam commented on src/main/java/edu/rice/habanero/benchmarks/BenchmarkRunner.java
> +        no_evaluation = argParser.getValue(new String[]{"--no_evaluation"}, no_evaluation);
Should we instead call this `simple` and have a corresponding variable `simpleExecutionRequested`?

2017-08-01 03:40 UTC, shamsimam commented on src/main/java/edu/rice/habanero/benchmarks/BenchmarkRunner.java
> +        if (no_evaluation) {
Instead of this `if`-block we should guard the console output statements in this method with `if (!simpleExecutionRequested) { ... }`

2017-08-01 03:40 UTC, shamsimam commented on src/main/java/edu/rice/habanero/benchmarks/CliArgumentParser.java
> + * @author <a href="http://shams.web.rice.edu/">Shams Imam</a> (shams@rice.edu)
You should set yourself as the author :)

2017-08-01 03:40 UTC, shamsimam commented on src/main/java/edu/rice/habanero/benchmarks/CliArgumentParser.java
> +    public int getValue(String key, int default_value) {
This should call the overloaded method: `getValue(new String[] {key}, default_value)`

2017-08-01 03:40 UTC, shamsimam commented on src/main/java/edu/rice/habanero/benchmarks/CliArgumentParser.java
> +    public int getValue(String key, int default_value) {
Please use camelCase in names, e.g. `defaultValue`.

2017-08-01 03:40 UTC, shamsimam commented on src/main/java/edu/rice/habanero/benchmarks/CliArgumentParser.java
> +    public int getValue(String key, int default_value) {
The same applies to the other `getValue` methods below.

2017-08-01 03:40 UTC, shamsimam commented on src/main/java/edu/rice/habanero/benchmarks/CliArgumentParser.java
> +    public int getValue(String[] key, int default_value) {
Can we create the helper method:
```
    public <V> V getValue(String[] key, Parser<V> parse, V defaultValue) {
        for (int i = 0; i < key.length; ++i) {
          String res = cliArgs.get(key[i]);
          if (res != null) {
              return parser.parse(res); 
          }
        }
        return defaultValue;
    }
```
Then we can use something like this:
```
public int getIntValue(String[] key, int defaultValue) {
  return getValue(key, (v) -> Integer.parseInt(v), defaultValue);
}
...
```
and have similar methods for `getLongValue`, `getStringValue`, `getBooleanValue`, etc.

2017-08-01 03:47 UTC, shamsimam commented on src/main/java/edu/rice/habanero/benchmarks/BenchmarkRunner.java
> +            for (int i = 0; i < iterations; i++) {
Should we force `iterations` to be equal to 1 when `no_evaluation` mode is enabled?

2017-08-24 16:46 UTC, aufgang001 commented
I'm going to fix the conflicts tomorrow.

Besides, for some reason I had problems with lambda functions you proposed in the file CliArgumentParser.java
So, I used the old school class based version to imitate lambdas.
Not that beautiful but it works.

2025-06-24 12:02 UTC, closed without merging